spring.application.name=UserService
server.servlet.context-path=/userService
spring.profiles.active=mysqlDB1
notificationServiceBaseUrl=http://localhost:8090/
springdoc-swagger-ui.path=/swagger-ui/index.html
#springdoc.api-docs.path=/api-docs
#http://localhost:8089/authService/swagger-ui/index.html
#http://localhost:8089/authService/v3/api-docs