package com.user.service.app.dtos.request;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Positive;

@Schema(
        name = "UserCreationRequest",
        description = "Request payload used by the Auth Service to create a user in the User Service"
)
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class UserCreationRequest {

    @Schema(
            description = "Unique user ID generated by the Auth Service",
            example = "1001",
            requiredMode = Schema.RequiredMode.REQUIRED
    )
    @NotNull(message = "Auth Service userId can't be null")
    @Positive(message = "Auth Service userId must be greater than 0")
    private Long authUserId;

    @Schema(
            description = "Unique username of the user",
            example = "amit.kumar",
            requiredMode = Schema.RequiredMode.REQUIRED
    )
    @NotBlank(message = "User Name can't be blank")
    private String userName;

    @Schema(
            description = "Email address of the user",
            example = "amit.kumar@example.com",
            requiredMode = Schema.RequiredMode.REQUIRED
    )
    @NotBlank(message = "User Email is required")
    @Email(message = "Email must be in proper format")
    private String userEmail;

    @Schema(
            description = "Password associated with the user account",
            example = "StrongPassword@123",
            requiredMode = Schema.RequiredMode.REQUIRED,
            format = "password"
    )
    @NotBlank(message = "User Password can't be empty")
    private String password;
}
